version: '3.8'

services:
  postgres:
    image: postgres:latest 
    container_name: businessplanner_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: businessplanner
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - businessplanner_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: businessplanner_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - businessplanner_network

volumes:
  postgres_data:

networks:
  businessplanner_network: